services:

  postgres:
    image: postgres:16
    ports:
      - "8090:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stream_studio
      - POSTGRES_PASSWORD=jXqUaFUT1F0URlaqIfBKRMQ04mrqr6Es

  postgres_test:
    image: postgres:16
    ports:
      - "9090:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stream_studio_test
      - POSTGRES_PASSWORD=jXqUaFUT1F0URlaqIfBKRMQ04mrqr6Es

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "VzS5chO1rnbP0NYGtCG9JWAaFcXQ2v0P"
    environment:
      - REDIS_REPLICATION_MODE=master


  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "EltuS1m7SLwCfHS8EgsTk82BZFhQwiLE"
    environment:
      - REDIS_REPLICATION_MODE=master
